### ISSUE TITLE
0.11.0-beta2: no valid kits generated

### ISSUE THREAD

**Issue by eldadroobol** [vector-of-bool/vscode-cmake-tools#282]
### Brief Issue Summary
Generated kit file contains no valid entries. 
The generated kit file is as follows:
`[
  {
    "name": "undefined - amd64",
    "visualStudioArchitecture": "amd64"
  },
  {
    "name": "undefined - amd64_arm",
    "visualStudioArchitecture": "amd64_arm"
  },
  {
    "name": "undefined - amd64_x86",
    "visualStudioArchitecture": "amd64_x86"
  },
  {
    "name": "undefined - x86",
    "visualStudioArchitecture": "x86"
  },
  {
    "name": "undefined - x86_amd64",
    "visualStudioArchitecture": "x86_amd64"
  },
  {
    "name": "undefined - x86_arm",
    "visualStudioArchitecture": "x86_arm"
  }
]`

Configuring is not possible since there are no valid kits to choose from.

### Expected:
- Start vscode without a cmake-kits.json file. It generates a kit file for you
- Try to select a kit, dropdown shows 'no entries to pick from'

### CMake Tools Log
2017-12-21T10:06:33.577Z [debug] [main] Safe constructing new CMakeTools instance
2017-12-21T10:06:33.578Z [debug] [kit] Constructing KitManager
2017-12-21T10:06:33.579Z [debug] [variant] Constructing VariantManager
2017-12-21T10:06:33.580Z [debug] [main] Constructing new CMakeTools instance
2017-12-21T10:06:33.581Z [debug] [main] Starting CMakeTools second-phase init
2017-12-21T10:06:33.582Z [debug] [rollbar] Checking Rollbar permissions
2017-12-21T10:06:33.582Z [debug] [rollbar] Rollbar enabled?  true
2017-12-21T10:06:33.768Z [info] [variant] Loaded new set of variants
2017-12-21T10:06:33.768Z [debug] [kit] Second phase init for KitManager
2017-12-21T10:06:33.777Z [debug] [kit] Rescanning for Kits
2017-12-21T10:06:33.777Z [debug] [kit] Scanning for Kits on system
2017-12-21T10:06:33.778Z [debug] [kit] Scanning directory C:\Windows\system32 for compilers
2017-12-21T10:06:33.778Z [debug] [kit] Scanning directory C:\Windows for compilers
2017-12-21T10:06:33.778Z [debug] [kit] Scanning directory C:\Windows\System32\Wbem for compilers
2017-12-21T10:06:33.778Z [debug] [kit] Scanning directory C:\Windows\System32\WindowsPowerShell\v1.0\ for compilers
2017-12-21T10:06:33.779Z [debug] [kit] Scanning directory C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common for compilers
2017-12-21T10:06:33.779Z [debug] [kit] Scanning directory C:\Program Files (x86)\Dr. Memory\bin\ for compilers
2017-12-21T10:06:33.779Z [debug] [kit] Scanning directory C:\Program Files\Microsoft VS Code\bin for compilers
2017-12-21T10:06:33.779Z [debug] [kit] Scanning directory C:\Program Files\CMake\bin for compilers
2017-12-21T10:06:33.779Z [debug] [kit] Scanning directory c:/home/bin/ for compilers
2017-12-21T10:06:33.831Z [debug] [kit] Found 0 kits in directory C:\Windows
2017-12-21T10:06:33.871Z [debug] [kit] Found 0 kits in directory C:\Windows\System32\Wbem
2017-12-21T10:06:33.874Z [debug] [kit] Found 0 kits in directory C:\Windows\System32\WindowsPowerShell\v1.0\
2017-12-21T10:06:33.875Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
2017-12-21T10:06:33.878Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Dr. Memory\bin\
2017-12-21T10:06:33.878Z [debug] [kit] Found 0 kits in directory C:\Program Files\Microsoft VS Code\bin
2017-12-21T10:06:33.879Z [debug] [kit] Found 0 kits in directory C:\Program Files\CMake\bin
2017-12-21T10:06:33.888Z [debug] [kit] Found 0 kits in directory c:/home/bin/
2017-12-21T10:06:34.255Z [debug] [kit] Found 0 kits in directory C:\Windows\system32
2017-12-21T10:06:34.265Z [debug] [kit] Checking for kit: undefined - x86
2017-12-21T10:06:34.265Z [debug] [kit] Checking for kit: undefined - amd64
2017-12-21T10:06:34.265Z [debug] [kit] Checking for kit: undefined - x86_amd64
2017-12-21T10:06:34.265Z [debug] [kit] Checking for kit: undefined - x86_arm
2017-12-21T10:06:34.266Z [debug] [kit] Checking for kit: undefined - amd64_arm
2017-12-21T10:06:34.266Z [debug] [kit] Checking for kit: undefined - amd64_x86
2017-12-21T10:06:34.289Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.2897278735376183.bat
2017-12-21T10:06:34.292Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.9690378926484022.bat
2017-12-21T10:06:34.296Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.34752570544913053.bat
2017-12-21T10:06:34.302Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.7976487994145876.bat
2017-12-21T10:06:34.303Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.6256844029111737.bat
2017-12-21T10:06:34.309Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.1317901545686837.bat
2017-12-21T10:06:37.463Z [info] [kit] Found Kit: undefined - x86
2017-12-21T10:06:37.464Z [info] [kit] Found Kit: undefined - amd64
2017-12-21T10:06:37.464Z [info] [kit] Found Kit: undefined - x86_amd64
2017-12-21T10:06:37.464Z [info] [kit] Found Kit: undefined - x86_arm
2017-12-21T10:06:37.464Z [info] [kit] Found Kit: undefined - amd64_arm
2017-12-21T10:06:37.464Z [info] [kit] Found Kit: undefined - amd64_x86
2017-12-21T10:06:37.464Z [debug] [kit] Saving news kits to C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json
2017-12-21T10:06:37.465Z [debug] [kit] C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json saved
2017-12-21T10:06:40.819Z [debug] [kit] Opening TextEditor for C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json
2017-12-21T10:06:40.819Z [debug] [main] Starting CMake driver
2017-12-21T10:06:40.906Z [debug] [driver] Base _init() of CMakeDriver
2017-12-21T10:06:40.906Z [info] [cms-client] Started new CMake Server instance with PID 11460
2017-12-21T10:06:41.915Z [debug] [cache] Reading CMake cache file c:\code\toolbox\build\CMakeCache.txt
2017-12-21T10:06:41.916Z [debug] [cache] Parsing CMake cache string
2017-12-21T10:06:42.089Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
2017-12-21T10:06:42.091Z [debug] [main] CMakeTools instance initialization complete.
2017-12-21T10:06:42.091Z [debug] [extension] Registering extension commands
2017-12-21T10:04:19.417Z [debug] [kit] Scanning directory C:\Program Files (x86)\Git\cmd for compilers
2017-12-21T10:04:19.417Z [debug] [kit] Scanning directory ~\bin\mplayer-svn-3756 for compilers
2017-12-21T10:04:19.418Z [debug] [kit] Scanning directory C:\Program Files (x86)\Graphviz2.38\bin for compilers
2017-12-21T10:04:19.418Z [debug] [kit] Scanning directory C:\Program Files (x86)\Dr. Memory\bin64\ for compilers
2017-12-21T10:04:19.426Z [warning] [kit] Failed to scan C:\Program Files\Git\usr\local\bin by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\Git\usr\local\bin'
2017-12-21T10:04:19.426Z [warning] [kit] Failed to scan C:\Program Files\Git\opt\bin by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\Git\opt\bin'
2017-12-21T10:04:19.427Z [warning] [kit] Failed to scan C:\Program Files\ConEmu\ConEmu\Scripts by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\ConEmu\ConEmu\Scripts'
2017-12-21T10:04:19.428Z [warning] [kit] Failed to scan C:\Program Files (x86)\LLVM\bin by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\LLVM\bin'
2017-12-21T10:04:19.429Z [warning] [kit] Failed to scan ~\bin by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\Microsoft VS Code\~\bin'
2017-12-21T10:04:19.429Z [warning] [kit] Failed to scan ~\bin\nc by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\Microsoft VS Code\~\bin\nc'
2017-12-21T10:04:19.430Z [warning] [kit] Failed to scan C:\Program Files (x86)\Git\bin by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Git\bin'
2017-12-21T10:04:19.430Z [warning] [kit] Failed to scan C:\Program Files (x86)\Git\cmd by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Git\cmd'
2017-12-21T10:04:19.430Z [warning] [kit] Failed to scan ~\bin\mplayer-svn-3756 by exception: Error: ENOENT: no such file or directory, stat 'C:\Program Files\Microsoft VS Code\~\bin\mplayer-svn-3756'
2017-12-21T10:04:19.471Z [debug] [kit] Found 0 kits in directory C:\home\bin
2017-12-21T10:04:19.529Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\usr\bin
2017-12-21T10:04:19.577Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\usr\bin
2017-12-21T10:04:19.583Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow
2017-12-21T10:04:19.594Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\MSBuild\14.0\bin
2017-12-21T10:04:19.599Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN
2017-12-21T10:04:19.602Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
2017-12-21T10:04:19.632Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE
2017-12-21T10:04:19.637Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages
2017-12-21T10:04:19.638Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\HTML Help Workshop
2017-12-21T10:04:19.645Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools
2017-12-21T10:04:19.688Z [debug] [kit] Found 0 kits in directory C:\Windows\Microsoft.NET\Framework\v4.0.30319
2017-12-21T10:04:19.707Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Windows Kits\8.1\bin\x86
2017-12-21T10:04:19.713Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools
2017-12-21T10:04:19.714Z [debug] [kit] Found 0 kits in directory C:\Program Files\ConEmu
2017-12-21T10:04:19.719Z [debug] [kit] Found 0 kits in directory C:\Program Files\ConEmu\ConEmu
2017-12-21T10:04:19.722Z [debug] [kit] Found 0 kits in directory C:\Windows\System32\WindowsPowerShell\v1.0
2017-12-21T10:04:19.754Z [debug] [kit] Found 0 kits in directory C:\Windows\System32\Wbem
2017-12-21T10:04:19.755Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
2017-12-21T10:04:19.758Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Dr. Memory\bin
2017-12-21T10:04:19.758Z [debug] [kit] Found 0 kits in directory C:\Program Files\Microsoft VS Code\bin
2017-12-21T10:04:19.770Z [debug] [kit] Found 0 kits in directory C:\Windows
2017-12-21T10:04:19.770Z [debug] [kit] Found 0 kits in directory C:\Program Files\CMake\bin
2017-12-21T10:04:19.781Z [debug] [kit] Found 0 kits in directory C:\home\bin\
2017-12-21T10:04:19.782Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\usr\bin\vendor_perl
2017-12-21T10:04:19.786Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\usr\bin\core_perl
2017-12-21T10:04:19.786Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\bin
2017-12-21T10:04:19.796Z [debug] [kit] Found 0 kits in directory C:\Program Files\Git\mingw64\bin
2017-12-21T10:04:19.800Z [debug] [kit] Found 0 kits in directory C:\code\scripts
2017-12-21T10:04:20.154Z [debug] [kit] Found 0 kits in directory C:\Windows\system32
2017-12-21T10:04:20.155Z [debug] [kit] Found 0 kits in directory C:\Program Files\CMake\bin
2017-12-21T10:04:20.161Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Meld
2017-12-21T10:04:20.163Z [debug] [kit] Found 0 kits in directory C:\Program Files\Python36
2017-12-21T10:04:20.173Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Graphviz2.38\bin
2017-12-21T10:04:20.185Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Graphviz2.38\bin
2017-12-21T10:04:20.188Z [debug] [kit] Found 0 kits in directory C:\Program Files (x86)\Dr. Memory\bin64\
2017-12-21T10:04:20.204Z [debug] [kit] Checking for kit: undefined - x86
2017-12-21T10:04:20.204Z [debug] [kit] Checking for kit: undefined - amd64
2017-12-21T10:04:20.205Z [debug] [kit] Checking for kit: undefined - x86_amd64
2017-12-21T10:04:20.205Z [debug] [kit] Checking for kit: undefined - x86_arm
2017-12-21T10:04:20.205Z [debug] [kit] Checking for kit: undefined - amd64_arm
2017-12-21T10:04:20.205Z [debug] [kit] Checking for kit: undefined - amd64_x86
2017-12-21T10:04:20.228Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.8427523251250579.bat
2017-12-21T10:04:20.233Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.9603460403360748.bat
2017-12-21T10:04:20.238Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.29162860787214817.bat
2017-12-21T10:04:20.242Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.25751402930748335.bat
2017-12-21T10:04:20.249Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.4098307817193694.bat
2017-12-21T10:04:20.262Z [info] [proc] Executing command: C:\Users\EROOBO~1.VID\AppData\Local\Temp\vs-cmt-0.46238734752837374.bat
2017-12-21T10:04:23.473Z [info] [kit] Found Kit: undefined - x86
2017-12-21T10:04:23.474Z [info] [kit] Found Kit: undefined - amd64
2017-12-21T10:04:23.474Z [info] [kit] Found Kit: undefined - x86_amd64
2017-12-21T10:04:23.474Z [info] [kit] Found Kit: undefined - x86_arm
2017-12-21T10:04:23.474Z [info] [kit] Found Kit: undefined - amd64_arm
2017-12-21T10:04:23.474Z [info] [kit] Found Kit: undefined - amd64_x86
2017-12-21T10:04:23.475Z [debug] [kit] Saving news kits to C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json
2017-12-21T10:04:23.477Z [debug] [kit] C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json saved
2017-12-21T10:04:28.890Z [debug] [kit] Opening TextEditor for C:\Users\eroobol.VIDIGODOMAIN\AppData\Roaming\CMakeTools\cmake-kits.json
2017-12-21T10:04:28.891Z [debug] [main] Starting CMake driver
2017-12-21T10:04:28.984Z [debug] [driver] Base _init() of CMakeDriver
2017-12-21T10:04:28.988Z [info] [cms-client] Started new CMake Server instance with PID 18236
2017-12-21T10:04:29.989Z [debug] [cache] Reading CMake cache file c:\code\toolbox\build\CMakeCache.txt
2017-12-21T10:04:29.990Z [debug] [cache] Parsing CMake cache string
2017-12-21T10:04:30.154Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
2017-12-21T10:04:30.155Z [debug] [main] CMakeTools instance initialization complete.
2017-12-21T10:04:30.155Z [debug] [extension] Registering extension commands
2017-12-21T10:04:30.359Z [debug] [extension] [1038] cmake.setVariant started
2017-12-21T10:04:32.182Z [debug] [main] Active build variant changed
2017-12-21T10:04:32.183Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
2017-12-21T10:04:32.183Z [debug] [main] No kit selected yet. Asking for a Kit first.
2017-12-21T10:04:32.183Z [debug] [kit] Opening kit selection QuickPick
2017-12-21T10:04:33.262Z [debug] [kit] User cancelled Kit selection
2017-12-21T10:04:33.262Z [debug] [main] No kit selected. Abort configure.
2017-12-21T10:04:33.262Z [debug] [extension] [1038] cmake.setVariant finished
2017-12-21T10:06:29.393Z [debug] [extension] Deactivate CMakeTools
2017-12-21T10:06:29.393Z [debug] [kit] Disposing KitManager
2017-12-21T10:06:29.393Z [debug] [main] Disposing CMakeTools extension
2017-12-21T10:06:29.394Z [debug] [kit] Disposing KitManager

### Platform and Versions

- **Operating System**: Windows 7
- **CMake Version**: 3.10.0
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.11.0-beta2
- **Compiler/Toolchain**: Visual C++ 2015

**Comment by KoeMai** [comment]
@vector-of-bool I think the problem is that vs2015 has no VsDevCmd.bat only a VSVARS32.BAT.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line

**Comment by vector-of-bool** [comment]
What output do you see from running vswhere? Use the one bundled with the extension, or the latest build from their github releases.

**Comment by eldadroobol** [comment]
For me, vswhere doesn't seem to output much of anything. Only the version of vswhere.

**Comment by KoeMai** [comment]
Can you try this
```
vswhere -all -format json -products * -legacy -prerelease
```

**Comment by eldadroobol** [comment]
Error 0x57: The "legacy" parameter cannot be specified with either the "products" or "requires" parameter

**Comment by vector-of-bool** [comment]
Did you try running the vswhere that comes bundled with the extension? I don't remember exactly where the files go on WIndows, but you should be able to find them and run the vswhere.exe that's in the `res` directory for the extension.

**Comment by MathiasMagnus** [comment]
I have a similar problem, though the reasons are most likely totally different.

Kit detection works now that #283 is solved, but the kit file generated is invalid.

```
[kit] Second phase init for KitManager
[kit] Re-read kits file from prior session
[kit] Re-reading kits file C:\Users\nagy-\AppData\Roaming\CMakeTools\cmake-kits.json
[kit] Invalid cmake-kits.json:
[kit]  >> [1]: should have required property 'compilers'
[kit]  >> [1]: should have required property 'toolchainFile'
[kit]  >> [1]: should have required property 'visualStudioVersion'
[kit]  >> [1]: should match exactly one schema in oneOf
[kit]  >> [2]: should have required property 'compilers'
[kit]  >> [2]: should have required property 'toolchainFile'
[kit]  >> [2]: should have required property 'visualStudioVersion'
[kit]  >> [2]: should match exactly one schema in oneOf
[kit] Successfully loaded 0 kits
[kit] Active kit set to null
[main] Starting CMake driver
```

The Kit file generated looks like this:

```JSON
PS C:\Users\nagy-> gc C:\Users\nagy-\AppData\Roaming\CMakeTools\cmake-kits.json
[
  {
    "name": "Clang 5.0.0",
    "compilers": {
      "C": "C:\\Kellekek\\LLVM\\5.0\\bin\\clang.exe",
      "CXX": "C:\\Kellekek\\LLVM\\5.0\\bin\\clang++.exe"
    }
  },
  {
    "name": "Visual Studio Build Tools 2017 - amd64",
    "visualStudio": "Visual Studio Build Tools 2017",
    "visualStudioArchitecture": "amd64",
    "preferredGenerator": {
      "name": "Visual Studio 15 2017",
      "platform": "x64"
    }
  },
  {
    "name": "Visual Studio Build Tools 2017 - x86",
    "visualStudio": "Visual Studio Build Tools 2017",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 15 2017"
    }
  }
]
```

When I invoke `vswhere.exe` manually, the one that ships with VS, found under `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe`, or to be more precise, the one that ships with the Build Tools Only installer of MSVC, it does not find the compiler.

```PowerShell
PS C:\Users\nagy-> & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -format json -all
[]
```

I did not find vswhere that comes with the extension (search Code install dir, AppData and all of Program Files, but nothing.

**Comment by vector-of-bool** [comment]
@MathiasMagnus, looking at your kits, I can see the problem, and it's a silly mistake: The JSON schema for the kits file wants `visualStudioVersion`, but the code uses `visualStudio`, which is why it won't validate. You can test a fix just by opening up the `kits-schema.json` in the installed extension and fixing the property name.

**Comment by vector-of-bool** [comment]
@MathiasMagnus, also, you need more arguments to vswhere to tell it to find the build tools. `-products *` should get it.

**Comment by eldadroobol** [comment]
For me, altering the property in the scheme to visualStudio and then manually entering kits works. The generated kits are still the same (as of beta3). I used the latest vswhere binary from github.

**Comment by vector-of-bool** [comment]
I believe I've got it all worked out. VS kits should now work properly in beta4! @eldadroobol, give it a try and close this issue if it seems fixed to your satisfaction.
