### ISSUE TITLE
Single file compilation doesn't work (with PowerShell as integrated terminal?)

### ISSUE THREAD

**Issue by MathiasMagnus** [vector-of-bool/vscode-cmake-tools#490]
### Brief Issue Summary

Launching a build of a single file from the CMake sidebar results in a garbled CLI invocation.

### Expected:

1. Push hammer next to file name
2. Compile the given file

### Apparent Behavior:

1. Push hammer next to file name
2. Get an error

```PowerShell
PS D:\onedrive\develop\tests\cmake\minimalcpp14\.vscode\cmake\build> 'C:KellekekMICROS~1VISUAL~1PreviewVCToolsMSVC1415~1.266binHostx64x64cl.exe' /nologo /TP /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 -std:c++14 /FoCMakeFilesMinimalCpp14.dirMain.cpp.obj /FdTARGET_COMPILE_PDB /FS -c D:OneDriveDevelopTestsCMakeMinimalCpp14Main.cpp
At line:1 char:78
+ ... S~1VISUAL~1PreviewVCToolsMSVC1415~1.266binHostx64x64cl.exe' /nologo / ...
+                                                                  ~
You must provide a value expression following the '/' operator.
At line:1 char:78
+ ... UAL~1PreviewVCToolsMSVC1415~1.266binHostx64x64cl.exe' /nologo /TP /DW ...
+                                                            ~~~~~~
Unexpected token 'nologo' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression
```

Slashes are missing from the compiler invocation. Perhaps some formatting goes wrong due to PowerShell not using the legacy cmd.exe, MS-DOS style `~1` shorthands for long and space containing file and folder names.

### Platform and Versions

- **Operating System**: Windows 10 (64-bit)
- **CMake Version**: 3.11.2
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0
- **Compiler/Toolchain**: Visual C++ 2017

**Comment by vector-of-bool** [comment]
Interesting. May need to use the `&` invoke operator? Or perhaps just quote _all_ arguments?

**Comment by svitalij** [comment]
@vector-of-bool ,

I'm having the same issue. And looks like i've found the problem:
On Windows compile_commands.json contains:

> "command": "C:\\\\Langs\\\\Mingw\\\\mingw64\\\\mingw32\\\\bin\\\\g++.exe    -g   -std=gnu++17 -o CMakeFiles\\\\primitives.dir\\\\main.cpp.obj -c E:\\\\Projects\\\\test\\\\main.cpp",

Note the delimiters. And shlex.split [in this line](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/compdb.ts#L33) does not support windows delimiters. 

I've fixed this by replacing all shlex.split calls with a simple function (in utils.js):
```javascript
function safeSplitCommand(p)
{
    p = replaceAll(p,'\\','/');
    var res = shlex.split(p);
    return res;
}
exports.safeSplitCommand = safeSplitCommand;
```

Mentioned line becomes:
```javascript
arguments: 'arguments' in cur ? cur.arguments : util.safeSplitCommand(cur.command),
```

Not sure this is a best possible fix, but works for me.

P.S. Thanks for the great extension!

**Comment by vector-of-bool** [comment]
The `\` character _shouldn't_ affect the behavior of shell splitting, so I'm not sure how/why your change makes it work? I'll do more investigation.

**Comment by svitalij** [comment]
Sure, but it does:

```typescript
let s = shlex.split("C:\\Langs\\Mingw\\mingw64\\mingw32\\bin\\g++.exe -g -std=gnu++17 -o CMakeFiles\\primitives.dir\\main.cpp.obj -c E:\\Projects\\test\\main.cpp");
console.log(s);
```
gives:
> Array[7]
>     0:"C:LangsMingwmingw64mingw32bing++.exe"
>     1:"-g"
>     2:"-std=gnu++17"
>     3:"-o"
>     4:"CMakeFilesprimitives.dirmain.cpp.obj"
>     5:"-c"
>     6:"E:Projectstestmain.cpp"

**Comment by MathiasMagnus** [comment]
Apologies for not responding. I'm on vacation with no devbox, just a phone. I can help out testing on Monday once I'm in the office and the problem is not resolved.

**Comment by vector-of-bool** [comment]
when I launch the terminal I don't specify a shell to execute. If I specify cmd.exe when compiling the file on Windows this should work alright. I'll give a few things a try.

**Comment by vector-of-bool** [comment]
I've changed the `shlex` module and it should now work correctly on Windows, and I'm also going to use cmd.exe as the shell for Windows since it has the syntax I'm expecting. Shell quoting for PowerShell is much more complicated.
